// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: g
func (_m *IHandler) Create(g *gin.Context) {
	_m.Called(g)
}

// Get provides a mock function with given fields: g
func (_m *IHandler) Get(g *gin.Context) {
	_m.Called(g)
}

// GetByID provides a mock function with given fields: g
func (_m *IHandler) GetByID(g *gin.Context) {
	_m.Called(g)
}

// Update provides a mock function with given fields: g
func (_m *IHandler) Update(g *gin.Context) {
	_m.Called(g)
}

// NewIHandler creates a new instance of IHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHandler {
	mock := &IHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
