version: '3.9'

services:
  app:
    container_name: gin-app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
      args:
       - APP_PORT="${APP_PORT}"
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: db
      DB_DRIVER: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
    restart: on-failure
    depends_on:
      - db
    command: ["/usr/local/bin/gin-example/wait-for-mysql.sh", "db", "/usr/local/bin/gin-example/init.sh"]
    volumes:
      - ./database/migrations:/gin-example/database/migrations
    networks:
      - gin
  
  db:
    container_name: gin-db
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ~/data/db/mysql/gin:/var/lib/mysql
    ports:
      - "${DB_PORT_CLIENT}:${DB_PORT_CLIENT}"
    networks:
      - gin
  
  redis:
    container_name: gin-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ~/data/db/redis/gin:/data
    networks:
      - gin

networks:
  gin:
    driver: bridge
