// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/rzfhlv/gin-example/internal/modules/invitation/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/rzfhlv/gin-example/pkg/param"
)

// IUsecase is an autogenerated mock type for the IUsecase type
type IUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, invitationPayload
func (_m *IUsecase) Create(ctx context.Context, invitationPayload model.Invitation) (model.Invitation, error) {
	ret := _m.Called(ctx, invitationPayload)

	var r0 model.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Invitation) (model.Invitation, error)); ok {
		return rf(ctx, invitationPayload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Invitation) model.Invitation); ok {
		r0 = rf(ctx, invitationPayload)
	} else {
		r0 = ret.Get(0).(model.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Invitation) error); ok {
		r1 = rf(ctx, invitationPayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, _a1
func (_m *IUsecase) Get(ctx context.Context, _a1 param.Param) ([]model.Invitation, int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []model.Invitation
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, param.Param) ([]model.Invitation, int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, param.Param) []model.Invitation); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, param.Param) int64); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, param.Param) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IUsecase) GetByID(ctx context.Context, id int64) (model.Invitation, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Invitation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Invitation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMemberID provides a mock function with given fields: ctx, memberID
func (_m *IUsecase) GetByMemberID(ctx context.Context, memberID int64) ([]model.InvitationDetail, error) {
	ret := _m.Called(ctx, memberID)

	var r0 []model.InvitationDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.InvitationDetail, error)); ok {
		return rf(ctx, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.InvitationDetail); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.InvitationDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, invitationPayload, id
func (_m *IUsecase) Update(ctx context.Context, invitationPayload model.Invitation, id int64) (model.Invitation, error) {
	ret := _m.Called(ctx, invitationPayload, id)

	var r0 model.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Invitation, int64) (model.Invitation, error)); ok {
		return rf(ctx, invitationPayload, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Invitation, int64) model.Invitation); ok {
		r0 = rf(ctx, invitationPayload, id)
	} else {
		r0 = ret.Get(0).(model.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Invitation, int64) error); ok {
		r1 = rf(ctx, invitationPayload, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUsecase creates a new instance of IUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUsecase {
	mock := &IUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
